# Generated by Django 4.1.4 on 2023-02-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_emailvalidationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailvalidationtoken',
            name='token',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token_hash',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='stock_table',
            name='full_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='stock_table',
            name='sector',
            field=models.CharField(max_length=60),
        ),
    ]
