# Generated by Django 4.1.4 on 2023-02-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_emailvalidationtoken_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailvalidationtoken',
            name='token',
            field=models.CharField(max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token_hash',
            field=models.CharField(max_length=2000, unique=True),
        ),
    ]
