# Generated by Django 4.1.4 on 2023-01-20 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='member_since',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
