# Generated by Django 4.1.4 on 2023-01-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='already_read',
            field=models.BooleanField(default=False),
        ),
    ]
