# Generated by Django 4.1.4 on 2023-01-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_notification_already_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
