# Generated by Django 4.1.4 on 2023-02-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_table',
            name='full_name',
            field=models.CharField(default='eewe', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock_table',
            name='sector',
            field=models.CharField(default='ewwww', max_length=30),
            preserve_default=False,
        ),
    ]
