# Generated by Django 4.1.4 on 2023-02-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_stock_table_full_name_stock_table_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified_email',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
