# Generated by Django 4.1.4 on 2023-02-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_user_verified_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verified_email',
            field=models.BooleanField(default=False),
        ),
    ]
